### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by qodunpob** [WEACOMRU/html-formatting#2]
- [x] Translate Readme to English
- [ ] Add npm script and instruction for run demo
- [x] Publish to NPM
